const sec = document.querySelector("section");
const p = sec.querySelector("p");
const button = sec.querySelector("button");

const quote = ['"I am selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can not handle me at my worst, then you sure as hell do not deserve me at my best.”','“So many books, so little time.”','“Two things are infinite: the universe and human stupidity; and I am not sure about the universe.”','“A room without books is like a body without a soul.”','“Be who you are and say what you feel, because those who mind do not matter, and those who matter do not mind.”','"You have gotta dance like there is nobody watching, Love like you will never be hurt, Sing like there is nobody listening, And live like it is heaven on earth.”','“You know you are in love when you can not fall asleep because reality is finally better than your dreams.”','“You only live once, but if you do it right, once is enough.”','“Be the change that you wish to see in the world.”','“In three words I can sum up everything I have learned about life: it goes on.”','“If you want to know what a man is like, take a good look at how he treats his inferiors, not his equals.”','“Do not walk in front of me… I may not follow Don’t walk behind me… I may not lead Walk beside me… just be my friend”','“If you tell the truth, you do not have to remember anything.”','“Friendship ... is born at the moment when one man says to another "What! You too? I thought that no one but myself . . .”','“I have learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.”','“A friend is someone who knows all about you and still loves you.”','“To live is the rarest thing in the world. Most people exist, that is all.”','“Always forgive your enemies; nothing annoys them so much.”','“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.”','“Live as if you were to die tomorrow. Learn as if you were to live forever.”','“We accept the love we think we deserve.”','“Without music, life would be a mistake.”','“I am so clever that sometimes I do not understand a single word of what I am saying.”','“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”','“Insanity is doing the same thing, over and over again, but expecting different results.”'];
const author = ["― Marilyn Monroe","― Frank Zappa","― Albert Einstein","― Marcus Tullius Cicero","― Bernard M. Baruch","― William W. Purkey","― Dr. Seuss","― Mae West","― Mahatma Gandhi","― Robert Frost","― J.K. Rowling, Harry Potter and the Goblet of Fire","― Albert Camus","― Mark Twain","― C.S. Lewis, The Four Loves","― Maya Angelou","― Elbert Hubbard","― Oscar Wilde","― Oscar Wilde","― Martin Luther King Jr., A Testament of Hope: The Essential Writings and Speeches","― Mahatma Gandhi","― Stephen Chbosky, The Perks of Being a Wallflower","― Friedrich Nietzsche, Twilight of the Idols","― Oscar Wilde, The Happy Prince and Other Stories","― Ralph Waldo Emerson","― Narcotics Anonymous"];

function randomQuote() {
    let value = Math.floor(Math.random()*25);
    let newQuote = quote[value];
    document.getElementById("quote").innerHTML = newQuote;
    let newAuthor = author[value];
    document.getElementById("author").innerHTML = newAuthor;  
}

button.addEventListener("click",randomQuote);